server.port=8080

max.token=f9LHodD0cOJTq0Il5FEwq5U6Z-Cyv1VS1ex35W0BXVbdTp3FxyfQGGB5wo1rejQ617ykC-jKR1UTOqfscbo2
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.reactor.netty.http.client=INFO
logging.level.reactor.netty.http.server=INFO
logging.level.org.springframework.web.reactive.function.client=INFO
logging.level.reactor.netty=INFO

rospatent.token=a9c9088643b043cf8085cf3a1b7d9188

spring.mvc.async.request-timeout=30000

