server.port=8080

max.api.token=${MAX_API_TOKEN}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.reactor.netty.http.client=INFO
logging.level.reactor.netty.http.server=INFO
logging.level.org.springframework.web.reactive.function.client=INFO
logging.level.reactor.netty=INFO

rospatent.token=a9c9088643b043cf8085cf3a1b7d9188


