server.port=8080

max.api.token=${MAX_API_TOKEN}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty=DEBUG

rospatent.token=${ROSPATENT_TOKEN}