package org.maxbot.miniapp.statemachine;

public enum BotEvents {
    USER_OPEN_CHAT,
    USER_SELECT_BASE,
    USER_INPUT_DATE,
    USER_SELECTED_DATE,

    USER_SELECT_SEARCH_ARRAY,
    USER_SELECT_CLASSIFIERS,

    USER_SEARCH_PATENT,

    USER_SELECT_FILTERS,
    USER_CONFIRM,
    SEARCH,
    BACK
}
