name: CI Coverage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # или 'gradle'

      - name: Run tests and generate JaCoCo report
        run: mvn test # или ./gradlew test jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: .github/badges

      - name: Commit badge if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update coverage badge"
          file_pattern: .github/badges/*.svg
